{{/* Make sure all variables are set properly */}}
{{- include "bjw-s.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "pod-gateway.harcodedValues" -}}
# -- Command starting DHCP server in the gateway
command:
- /bin/gateway_sidecar.sh

securityContext:
  capabilities:
    add:
      - NET_RAW
      - NET_ADMIN

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    enabled: true
    type: custom
    mountPath: /config
    readOnly: true
    volumeSpec:
      configMap:
        name: {{ include "pod-gateway.configmap" . }}
        defaultMode: 0555

initContainers:
  routes:
    image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command:
    - /bin/gateway_init.sh
    securityContext:
      privileged: true
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
  coredns:
    dependsOn:
      - routes
    image:
      repository: mirror.gcr.io/coredns/coredns
      tag: 1.12.1
    args:
      - -conf
      - /etc/coredns/corefile
    restartPolicy: Always

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    type: ClusterIP
    clusterIP: None
    ports:
      http:
        port: 4789
        protocol: UDP
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "pod-gateway.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}