{{/* Make sure all variables are set properly */}}
{{- include "bjw-s-labs.common.loader.init" . }}

{{/* Append the hardcoded settings */}}
{{- define "pod-gateway.harcodedValues" -}}
# -- Command starting DHCP server in the gateway
command:
- /bin/gateway_sidecar.sh

securityContext:
  capabilities:
    add:
      - NET_RAW
      - NET_ADMIN

# -- Configure persistence settings for the chart under this key.
persistence:
  config:
    type: configMap
    name: {{ include "pod-gateway.configmap" . }}
    advancedMounts:
      pod-gateway:
        pod-gateway:
          - path: /config
            readOnly: true
  coredns:
    type: configMap
    name: {{ include "pod-gateway.configmap" . }}-coredns
    advancedMounts:
      pod-gateway:
        coredns:
          - path: /etc/coredns/corefile
            subPath: corefile
            readOnly: true

initContainers:
  routes:
    image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command:
    - /bin/gateway_init.sh
    securityContext:
      privileged: true

  coredns:
    image:
      repository: {{ .Values.initContainers.coredns.repository | default "mirror.gcr.io/coredns/coredns" | quote }}
      tag: {{ .Values.initContainers.coredns.tag | default "1.12.1" | quote }}
    args:
      - -conf
      - /etc/coredns/corefile
    restartPolicy: {{ .Values.initContainers.coredns.restartPolicy | default "Always" | quote }}

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

service:
  main:
    type: ClusterIP
    clusterIP: None
    ports:
      http:
        port: 4789
        protocol: UDP
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "pod-gateway.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s-labs.common.loader.all" . }}