{{- include "bjw-s.common.loader.init" . -}}
{{- range $namespace := append .Values.routed_namespaces .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-gateway.configmap" $ | quote }}-coredns
  namespace: {{ $namespace }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" $ | nindent 4 }}
data:                                                                                                        
    corefile: |-                                                                                               
      .:53 {
          bind 127.0.0.2                                                                                       
          rewrite stop type AAAA A                                                                             
          errors                                                                                               
          health :8081 {                                                                                       
              lameduck 5s                                                                                      
          }                                                                                                    
          log {                                                                                                
              class error                                                                                      
          }                                                                                                    
          forward . tls://9.9.9.9 tls://149.112.112.112 {                                                      
              tls_servername dns.quad9.net                                                                     
              policy sequential                                                                                
              health_check 5s                                                                                  
          }                                                                                                    
          reload                                                                                               
      }                                                                                                        
                                                                                                               
      cluster.local:53 {                                                                                       
          bind 127.0.0.2                                                                                       
          rewrite stop type AAAA A                                                                             
          errors                                                                                               
          log {                                                                                                
              class error                                                                                      
          }                                                                                                    
          forward . 172.17.0.10                                                                                
      }