---
name: Helm Chart Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  #publish-oci-chart:
  #  name: Publish Helm Chart as OCI Artifact
  #  runs-on: ubuntu-latest
  #  needs: prepare
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #
  #    - name: Set up Helm
  #      uses: azure/setup-helm@v4
  #      with:
  #        version: v3.14.4
  #
  #    - name: Package chart
  #      run: |
  #        helm dependency update charts/pod-gateway
  #        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
  #          VERSION_TAG="${GITHUB_REF##*/}"
  #          helm package charts/pod-gateway --version "${VERSION_TAG#v}" --destination packaged
  #          CHART_FILE=$(ls packaged/pod-gateway-*.tgz)
  #          cp "$CHART_FILE" "packaged/pod-gateway-chart-${VERSION_TAG#v}.tgz"
  #        else
  #          helm package charts/pod-gateway --version latest --destination packaged
  #          CHART_FILE=$(ls packaged/pod-gateway-*.tgz)
  #          cp "$CHART_FILE" "packaged/pod-gateway-chart-latest.tgz"
  #        fi
  #
  #    - name: Push chart to OCI registry
  #      run: |
  #        helm registry login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
  #        for tgz in packaged/pod-gateway-chart-*.tgz; do
  #          helm push "$tgz" oci://ghcr.io/${{ github.repository_owner }}/pod-gateway-chart
  #          echo "Published $tgz to OCI registry: ghcr.io/${{ github.repository_owner }}/pod-gateway-chart"
  #        done

  render-templates:
    name: Render Helm Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Render Helm templates with default values
        env:
          KUBERNETES_VERSION: v1.32.0
        run: |
          helm dependency update charts/pod-gateway
          helm template pod-gateway charts/pod-gateway --namespace test --values charts/pod-gateway/values.yaml --kube-version $KUBERNETES_VERSION > rendered.yaml

      - name: Check for YAML syntax errors
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: rendered.yaml

      - name: Upload rendered YAML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-yaml
          path: rendered.yaml

      - name: Summarize rendered templates
        run: |
          echo "Rendered Helm templates for pod-gateway with default values."
          ls -lh rendered.yaml